Vagrant.configure("2") do |config|
  # First creating the database
  config.vm.define "db-server" do |db|
    db.vm.box = "ubuntu/focal64"
    db.vm.hostname = "db-server"
    db.vm.network "private_network", ip: "192.168.1.100"
    
    db.vm.provision "shell", inline: <<-SHELL
      # Update and install MySQL server
      sudo apt-get update
      sudo apt-get install -y mysql-server
      sudo systemctl start mysql
      sudo systemctl enable mysql
      
    mysql -u root -e 'CREATE DATABASE wordpress;'
    mysql -u root -e 'CREATE USER wordpress@% IDENTIFIED BY "1234567890";'
    mysql -u root -e 'GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER ON wordpress.* TO wordpress@%;'
    mysql -u root -e 'FLUSH PRIVILEGES;'

    systemctl restart mysql
    SHELL
  end
end
