Vagrant.configure("2") do |config|
  # First creating the database
  config.vm.define "db-server" do |db|
    db.vm.box = "ubuntu/focal64"
    db.vm.hostname = "db-server"
    db.vm.network "public_network", ip: "192.168.0.155"
    
    db.vm.provision "shell", inline: <<-SHELL
      # Update and install MySQL server
      sudo apt-get update
      sudo apt-get install -y mysql-server
      sudo systemctl start mysql
      sudo systemctl enable mysql
      
      # Write SQL commands to a file
      echo "CREATE DATABASE wordpress;
      CREATE USER 'wordpress'@'%' IDENTIFIED BY 'wordpress';
      GRANT ALL PRIVILEGES ON wordpress.* TO 'wordpress'@'%';
      FLUSH PRIVILEGES;" > /tmp/setup.sql
      
      # Run the SQL file
      sudo mysql < /tmp/setup.sql
    SHELL
  end
end
